"""commetn add likeCount column

Revision ID: 0c275d428496
Revises: eb36531b1171
Create Date: 2021-05-18 11:15:59.466494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c275d428496'
down_revision = 'eb36531b1171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likeCount', sa.Integer(), nullable=True, comment='点赞的人数'))
    op.create_foreign_key(None, 'poemWriters', 'users', ['userId'], ['id'])
    op.alter_column('poems', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poems', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'poemWriters', type_='foreignkey')
    op.drop_column('comments', 'likeCount')
    # ### end Alembic commands ###
