"""init migration

Revision ID: 317a09980bca
Revises: 
Create Date: 2021-05-02 15:55:24.702813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317a09980bca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poemStyles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('style', sa.String(length=4), nullable=True, comment='风格'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poemTypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=True, comment='体裁 词牌等'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poemWriters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('writer', sa.String(length=8), nullable=False, comment='作者'),
    sa.Column('dynasty', sa.String(length=4), nullable=False, comment='朝代'),
    sa.Column('introduction', sa.String(), nullable=True, comment='生平介绍'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('nickName', sa.String(length=8), nullable=True, comment='昵称'),
    sa.Column('password', sa.String(length=128), nullable=True, comment='密码哈希'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('poems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False, comment='名称'),
    sa.Column('dynasty', sa.String(length=4), nullable=False, comment='朝代'),
    sa.Column('writerId', sa.Integer(), nullable=True, comment='作者id'),
    sa.Column('typeId', sa.Integer(), nullable=True, comment='体裁'),
    sa.Column('styleId', sa.Integer(), nullable=True, comment='风格id'),
    sa.Column('content', sa.String(), nullable=False, comment='内容'),
    sa.Column('comment', sa.String(), nullable=True, comment='评论'),
    sa.ForeignKeyConstraint(['styleId'], ['poemStyles.id'], ),
    sa.ForeignKeyConstraint(['typeId'], ['poemTypes.id'], ),
    sa.ForeignKeyConstraint(['writerId'], ['poemWriters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('likePoems',
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('poemId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['poemId'], ['poems.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likePoems')
    op.drop_table('poems')
    op.drop_table('users')
    op.drop_table('poemWriters')
    op.drop_table('poemTypes')
    op.drop_table('poemStyles')
    # ### end Alembic commands ###
