"""add comment table 

Revision ID: d046074ebdb2
Revises: 6a68c308b10b
Create Date: 2021-05-04 10:24:53.489848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd046074ebdb2'
down_revision = '6a68c308b10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('content', sa.String(length=140), nullable=True, comment='点评内容'),
    sa.Column('userId', sa.Integer(), nullable=True, comment='点评人的id'),
    sa.Column('poemId', sa.Integer(), nullable=True, comment='诗词id'),
    sa.ForeignKeyConstraint(['poemId'], ['poems.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    # ### end Alembic commands ###
