"""poemWriters table add userId column

Revision ID: eb36531b1171
Revises: d046074ebdb2
Create Date: 2021-05-06 09:52:52.339247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb36531b1171'
down_revision = 'd046074ebdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poemWriters', sa.Column('userId', sa.Integer(), nullable=True, comment='用户id'))
    op.create_foreign_key(None, 'poemWriters', 'users', ['userId'], ['id'])
    op.alter_column('poems', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('poems', 'comment',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'poemWriters', type_='foreignkey')
    op.drop_column('poemWriters', 'userId')
    # ### end Alembic commands ###
